# Mage Inferno Docker Compose (https://github.com/mageinferno/magento2-docker-compose)
# Version 2.1.0

app:
  image: docker-nginx
  ports:
    - "8088:80"
  links:
    - php-fpm
    - db
  volumes_from:
    - appdata
  environment:
    - APP_MAGE_MODE=production
    - VIRTUAL_HOST=dockermag_app_1.docker

appdata:
  image: tianon/true
  volumes:
    - ~/.composer:/root/.composer
    - ./src:/src
    - ./config/nginx:/etc/nginx/templates
    - ./volumes/nginx/conf.d:/etc/nginx/conf.d
    - ./logs/nginx:/var/log/nginx/log

"php-fpm":
  image: docker-php
  links:
    - db
  volumes_from:
    - appdata
  environment:
    - APP_MAGE_MODE=production
    - PHP_MEMORY_LIMIT=4G

db:
  image: mariadb:10.1.10
  ports:
    - "3306:3306"
  volumes_from:
    - dbdata
  environment:
    - MYSQL_ROOT_PASSWORD=magento2
    - MYSQL_DATABASE=magento2
    - MYSQL_USER=magento2
    - MYSQL_PASSWORD=magento2

dbdata:
  image: tianon/true
  volumes:
    - /var/lib/mysql

setup:
  image: mageinferno/magento2-php:7.0.2-fpm-0
  command: /usr/local/bin/mage-setup
  links:
    - db
  volumes_from:
    - appdata
  environment:
    - M2SETUP_DB_HOST=db
    - M2SETUP_DB_NAME=magento2
    - M2SETUP_DB_USER=magento2
    - M2SETUP_DB_PASSWORD=magento2
    - M2SETUP_BASE_URL=http://dockermag_app_1.docker:8088/
    - M2SETUP_ADMIN_FIRSTNAME=Admin
    - M2SETUP_ADMIN_LASTNAME=User
    - M2SETUP_ADMIN_EMAIL=dummy@gmail.com
    - M2SETUP_ADMIN_USER=magento2
    - M2SETUP_ADMIN_PASSWORD=magento2
    - M2SETUP_VERSION=2.0.0
    - M2SETUP_USE_SAMPLE_DATA=true
